In [2]:
import itertools
import numpy as np

In [3]:
joint_count = np.zeros((3,5)) # Initial any value and change later
joint_count

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [4]:
outcome_space = list(itertools.product('123456', repeat=4))

In [5]:
for event in outcome_space:
    x, y = 0, 0
    count = 1
    for value in event:
        if value == '1' or value == '2':
            y = y + 1
            if count < 3:
                x = x + 1
        count = count + 1
    joint_count[x,y] = joint_count[x,y] + 1

In [6]:
joint_prob = joint_count/len(outcome_space)
print(joint_prob)

[[0.19753086 0.19753086 0.04938272 0.         0.        ]
 [0.         0.19753086 0.19753086 0.04938272 0.        ]
 [0.         0.         0.04938272 0.04938272 0.01234568]]


In [7]:
p_x = np.sum(joint_prob, axis=1) # axis = 1, sum by row 
p_y = np.sum(joint_prob, axis=0) # axis = 0, sum by column
print ('p_x0, p_x1, p_x2 respectively ', p_x)
print ('p_y0, p_y1, p_y2, p_y3, p_y4 respectively', p_y)  

p_x0, p_x1, p_x2 respectively  [0.44444444 0.44444444 0.11111111]
p_y0, p_y1, p_y2, p_y3, p_y4 respectively [0.19753086 0.39506173 0.2962963  0.09876543 0.01234568]


In [8]:
p_x_given_y, p_y_given_x = joint_prob, joint_prob # Just initially

for x in range(0,3):
    for y in range(0,5):
        p_x_given_y[x,y] = p_x_given_y[x,y]/p_y[y]

print(p_x_given_y)


for x in range(0,3):
    for y in range(0,5):
        p_y_given_x[x,y] = p_y_given_x[x,y]/p_x[x]
        print(p_x[x])

print(p_y_given_x)

[[ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]]
[[ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]]
[[1.         0.5        0.16666667 0.         0.        ]
 [0.         0.5        0.66666667 0.5        0.        ]
 [0.         0.         0.16666667 0.5        1.        ]]
0.4444444444444444
0.4444444444444444
0.4444444444444444
0.4444444444444444
0.4444444444444444
0.4444444444444444
0.4444444444444444
0.4444444444444444
0.4444444444444444
0.4444444444444444
0.1111111111111111
0.1111111111111111
0.1111111111111111
0.1111111111111111
0.1111111111111111
[[2.25  1.125 0.375 0.    0.   ]
 [0.    1.125 1.5   1.125 0.   ]
 [0.    0.    1.5   4.5   9.   ]]


In [9]:
joint_prob

array([[2.25 , 1.125, 0.375, 0.   , 0.   ],
       [0.   , 1.125, 1.5  , 1.125, 0.   ],
       [0.   , 0.   , 1.5  , 4.5  , 9.   ]])